"use strict";var LeanParser=(()=>{var d=Object.defineProperty;var B=Object.getOwnPropertyDescriptor;var w=Object.getOwnPropertyNames;var C=Object.prototype.hasOwnProperty;var S=(e,i)=>{for(var n in i)d(e,n,{get:i[n],enumerable:!0})},D=(e,i,n,r)=>{if(i&&typeof i=="object"||typeof i=="function")for(let s of w(i))!C.call(e,s)&&s!==n&&d(e,s,{get:()=>i[s],enumerable:!(r=B(i,s))||r.enumerable});return e};var I=e=>D(d({},"__esModule",{value:!0}),e);var T={};S(T,{expandCommentBlock:()=>k,parseLean:()=>P,splitLeanDocComments:()=>x,splitMarkdownSections:()=>b});function x(e,i){let n=[],r=0,s=0;for(;r<e.length;){let t=e.indexOf("/-!",r),l=e.indexOf("/--",r),c=-1,u=null;if(t!==-1&&(l===-1||t<l)?(c=t,u="module-doc"):l!==-1&&(c=l,u="doc-comment"),c===-1)break;c>s&&o(e.slice(s,c));let p=c+3,g=M(e,p);if(g===-1){o(e.slice(c)),s=e.length;break}let h=e.slice(p,g);a(u,h,c,g),r=g+2,s=r}return s<e.length&&o(e.slice(s)),n.filter(t=>t.type==="code"||t.type==="mermaid"||t.type==="graphviz"?t.source.trim().length>0:t.type==="svg-file"?t.path.trim().length>0:t.content.trim().length>0);function o(t){let l=t.split(`
`),c=0;for(;c<l.length&&l[c].trim()==="";)c++;if(!i){let m=e.slice(0,s).split(`
`).length-1+c,f=L(t),y=f.split(`
`).length,v=m+(y>0?y-1:0);n.push({type:"code",source:f,range:{startLine:m,endLine:v}});return}let p=i.positionAt(s).line+c,g=i.positionAt(s+t.length);n.push({type:"code",source:L(t),range:{startLine:p,endLine:g.line}})}function a(t,l,c,u){let p=z(l);if(!i){let m=e.slice(0,c).split(`
`).length-1,f=m+(l.split(`
`).length-1);n.push({type:t,content:p,range:{startLine:m,endLine:f}});return}let g=i.positionAt(c),h=i.positionAt(u+2);n.push({type:t,content:p,range:{startLine:g.line,endLine:h.line}})}}function z(e){let i=e.split(`
`),n=1/0;for(let s=1;s<i.length;s++){let o=i[s];if(o.trim().length===0)continue;let a=o.match(/^\s*/)?.[0].length??0;a<n&&(n=a)}return n===1/0&&(n=0),i.map((s,o)=>o===0?s.trim():s.trim().length===0?"":s.length>=n?s.slice(n):s.trim()).join(`
`).trim()}function L(e){let i=e.split(`
`),n=0;for(;n<i.length&&i[n].trim()==="";)n++;let r=i.length-1;for(;r>=0&&i[r].trim()==="";)r--;return n>r?"":i.slice(n,r+1).join(`
`)}function A(e){let i=[],n=/^```(mermaid|graphviz|dot)\s*\n([\s\S]*?)^```\s*$/gm,r=/^@svg\s+(.+)$/gm,s=[],o;for(;(o=n.exec(e))!==null;){let l=o[1]==="mermaid"?"mermaid":"graphviz";s.push({index:o.index,end:n.lastIndex,type:l,data:o[2]})}for(;(o=r.exec(e))!==null;)s.push({index:o.index,end:r.lastIndex,type:"svg-file",data:o[1].trim()});s.sort((t,l)=>t.index-l.index);let a=0;for(let t of s){let l=e.substring(a,t.index);l.trim().length>0&&i.push({type:"text",content:l.trim()}),t.type==="svg-file"?i.push({type:"svg-file",path:t.data}):t.data.trim().length>0&&i.push({type:t.type,source:L(t.data)}),a=t.end}if(a<e.length){let t=e.substring(a);t.trim().length>0&&i.push({type:"text",content:t.trim()})}return i.length===0&&e.trim().length>0&&i.push({type:"text",content:e.trim()}),i}function b(e){let i=e.split(`
`),n=[],r=[],s=!1,o="";for(let a of i){let t=a.match(/^(\s*)(`{3,}|~{3,})/);t&&(s?a.trim().startsWith(o.repeat(3))&&(s=!1):(s=!0,o=t[2][0])),!s&&/^#{1,2}\s/.test(a)&&r.length>0&&(n.push(r.join(`
`)),r=[]),r.push(a)}return r.length>0&&n.push(r.join(`
`)),n}function k(e){if(e.type!=="module-doc"&&e.type!=="doc-comment")return[e];let i=A(e.content),n=[];for(let r of i)if(r.type==="text"){let s=b(r.content);for(let o of s)o.trim().length>0&&n.push({type:e.type,content:o.trim(),range:e.range})}else r.type==="svg-file"?n.push({type:"svg-file",path:r.path,range:e.range}):n.push({type:r.type,source:r.source,range:e.range});return n}function M(e,i){let n=i,r=null,s=!1;for(;n<e.length;){let o=e[n];if(o==="`"){let t=1;for(;n+t<e.length&&e[n+t]==="`";)t++;if(r===null){if(t>=3){let l=n-1;for(;l>=0&&e[l]!==`
`;)l--;let c=l+1,u=e.slice(c,n);if(/^\s*$/.test(u)){s=!s,n+=t;continue}}if(!s){r=t,n+=t;continue}}else if(t===r){r=null,n+=t;continue}n+=t;continue}let a=n+1<e.length?e[n+1]:"";if(!s&&r===null&&o==="-"&&a==="/")return n;n+=1}return-1}function P(e,i){return x(e,i).flatMap(n=>k(n))}return I(T);})();
